### ISSUE TITLE
hip_imaging dataset

### ISSUE THREAD

**Issue by lkccu** [arcadelab/SyntheX#2]
Hi professor @gaocong13 ,thanks in advance for your great work in solving the issue of lacking of dataset in xray/ct dataset. 

I am tring to run the code in the guidance of "readme.md" of hip_imaging, which mentioned `The paired images and labels (segmentation and landmark) are structured in HDF5 files. They are located in data/hip_imaging/controlled_study. `However,I cant find them anywhere in the repo.Are them not public now or anything else?Please give a hand!

Thank you very much!

**Comment by lkccu** [comment]
I have found em in the paper. Thank you!

**Comment by CYXYZ** [comment]
Hi Ikccu, can you share the dataset files with me?
